# Generated by Django 5.1.4 on 2024-12-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_delete_gallerys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Gallerys',
        ),
    ]
