# Generated by Django 5.1.4 on 2024-12-09 14:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_delete_gallerys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
