# Generated by Django 5.1.4 on 2024-12-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='destination_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
